topInformation:
  # If true, the outputs of the current recipe will be displayed.
  # Default: true
  displayRecipeOutputs: true

  # If true, only the name of item and fluid will be displayed.
  # Default: false
  conciseMode: false

  # Each line can have a maximum of several items, which only take effect when displayItemName is false.
  # Default: 8
  itemsPerLine: 8

  # If true, the maintenance information of the current machine will be displayed.
  # Default: true
  displayMaintenanceInfo: true

  # If true, the exhaust vent information of the current machine will be displayed.
  # Default: true
  displayExhaustVentInfo: true

  # If true, the auto output information of the current machine will be displayed.
  # Default: true
  displayAutoOutputInfo: true

  # If true, the voltage and amperage of the current cable will be displayed.
  # Default: true
  displayCableInfo: true

  # If true, The current mode of the machine will be displayed.
  # Default: true
  displayMachineMode: true

  # If true, Display whether it is currently formed or not.
  # Default: true
  displayMulitblockStructure: true

  # If true, Display stained color in pipe or other stain block
  # Default: true
  displayStainedColor: true

  # If true, Display parallel of the machine or hatch
  # Default: true
  displayParallel: true

oreVeinDisplay:
  # If true, the ore vein display will be displayed using an NH-style dimension.
  # Default: true
  useNHDimensionDisplay: true

  # If true, the dimension display will show dimension tier.
  # Default: false
  showDimensionTier: true

  # To add custom display dimensions.
  dimensions:
    - ad_astra:moon$1
    - ad_astra:mars$2
    - ad_astra:venus$4
    - ad_astra:mercury$4
    - ad_astra:glacio$5

